# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "01:01"
    commit-message:
      prefix: deps
    groups:
      all:
        patterns:
          - "*"
  # # https://github.com/dependabot/dependabot-core/issues/6067
  # - package-ecosystem: docker
  #   directory: /
  #   schedule:
  #     interval: weekly
  #     day: monday
  #     time: "01:01"
  #   commit-message:
  #     prefix: deps
  #   groups:
  #     all:
  #       patterns:
  #         - "*"
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "01:01"
    commit-message:
      prefix: deps
    groups:
      all:
        patterns:
          - "*"
